apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: b2b
  labels:
    strimzi.io/cluster: logs-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    retention.ms: 3600
    segment.bytes: 1073741824
