apiVersion: v1
kind: Service
metadata:
  name: pluralizer-ui
spec:
  selector:
    app: pluralizer-ui
  type: ClusterIP
# type: ClusterIP
# type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
