---
apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        app: db
spec:
    ports:
        - port: 5432
          name: db
    clusterIP: None
    selector:
        app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: db
spec:
    serviceName: db
    replicas: 1
    selector:
        matchLabels:
            app: db
    template:
        metadata:
            labels:
                app: db
        spec:
            containers:
                - name: db
                  image: postgres:13.1-alpine
                  args: [ "-c", "statement_timeout=60s" ]
                  env:
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres
                                key: postgres.postgres.password
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: db-data
                        subPath: postgres
    volumeClaimTemplates:
        - metadata:
              name: db-data
          spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                  requests:
                      storage: 100Mi
